site_name: LightRoute
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: de
  font:
    text: Lato
    code: JetBrains Mono
  features:
    - tabs
    - instant
  palette:
    primary: manticore-blue
    accent: manticore-orange
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  #static_templates:
  #  - 404.html
  #  - offline.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
markdown_extensions:
  - codehilite